/* ─────────────────────────────────────────────────────────────────────────
   Code template generators — each function returns a clean JSX string
   that can be copied into a project.
   Using String concatenation (not nested template literals) to avoid
   interpolation clashes.
───────────────────────────────────────────────────────────────────────── */

// ── Feature 1 ─────────────────────────────────────────────────────────────
export function generateTagBoardCode(config: Record<string, any>): string {
  const cardCount = Number(config.cardCount ?? 12);
  const columns = Number(config.columns ?? 4);

  const gridColClass =
    columns === 1
      ? "grid-cols-1"
      : columns === 2
      ? "grid-cols-1 md:grid-cols-2"
      : columns === 3
      ? "grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
      : "grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4";

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Student Class Assignment Board",
    " * Dependencies: @dnd-kit/core  @dnd-kit/utilities  lucide-react",
    " */",
    "",
    'import React, { useState, useMemo } from "react";',
    'import { DndContext, DragOverlay, PointerSensor, MouseSensor, TouchSensor, useSensor, useSensors, useDraggable, useDroppable } from "@dnd-kit/core";',
    'import { CSS } from "@dnd-kit/utilities";',
    'import { UserCircle2, Users, Search, X } from "lucide-react";',
    "",
    "interface Person { id: string; name: string; }",
    "",
    "/* ── Mock roster (replace with your API call) ── */",
    "const STUDENTS: Person[] = [",
    '  { id: "s01", name: "Alice Johnson" },',
    '  { id: "s02", name: "Bob Smith" },',
    '  { id: "s03", name: "Carol Williams" },',
    '  // ... add more students',
    "];",
    "",
    "const CARDS = Array.from({ length: " + cardCount + " }, (_, i) => ({",
    "  id: `card-${i + 1}`,",
    "  label: `Class ${i + 1}`,",
    "}));",
    "",
    "/* ── PersonChip — drag from anywhere ─────────── */",
    "function PersonChip({ person, inCard, assignedTo, onRemove, overlay, sourceId }: {",
    "  person: Person; inCard?: boolean; assignedTo?: string; onRemove?: () => void;",
    "  overlay?: boolean; sourceId?: string;",
    "}) {",
    "  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({",
    "    id: sourceId ?? `person-${person.id}`,",
    "    data: { person },",
    "    disabled: overlay,",
    "  });",
    "  const style = transform ? { transform: CSS.Translate.toString(transform) } : undefined;",
    "",
    "  if (overlay) return (",
    '    <div className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg bg-blue-600 text-white text-xs font-bold shadow-xl cursor-grabbing pointer-events-none">',
    "      <UserCircle2 size={13} /><span>{person.name}</span>",
    "    </div>",
    "  );",
    "",
    "  return (",
    "    <div ref={setNodeRef} style={style} {...listeners} {...attributes}",
    "      className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold border select-none cursor-grab active:cursor-grabbing transition-all",
    "        ${isDragging ? 'opacity-20 scale-90' : inCard",
    "          ? 'bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100 dark:bg-blue-950/50 dark:text-blue-300 dark:border-blue-800'",
    "          : assignedTo",
    "          ? 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800'",
    "          : 'bg-white text-slate-700 border-slate-200 hover:border-blue-300 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700'",
    "        }`}",
    "    >",
    "      <UserCircle2 size={12} className=\"opacity-60\" />",
    "      <span>{person.name}</span>",
    "      {assignedTo && !inCard && (",
    '        <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-100 text-amber-600 dark:bg-amber-900/50 dark:text-amber-400">{assignedTo}</span>',
    "      )}",
    "      {inCard && onRemove && (",
    "        <button onPointerDown={(e)=>e.stopPropagation()} onClick={(e)=>{e.stopPropagation();onRemove();}}",
    '          className="w-4 h-4 flex items-center justify-center rounded hover:bg-blue-200 dark:hover:bg-blue-800 text-blue-400 cursor-pointer">',
    "          <X size={10} />",
    "        </button>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "/* ── ClassCard ───────────────────────────────── */",
    "function ClassCard({ id, label, people, onRemove }: { id: string; label: string; people: Person[]; onRemove: (pid: string) => void }) {",
    "  const { setNodeRef, isOver } = useDroppable({ id });",
    "  return (",
    "    <div ref={setNodeRef}",
    "      className={`flex flex-col rounded-xl border min-h-[160px] transition-all overflow-hidden",
    "        ${isOver ? 'border-blue-500 shadow-lg ring-2 ring-blue-500/20 scale-[1.02]' : 'border-slate-200 dark:border-slate-800'}`,",
    "    }>",
    "      <div className={`flex items-center justify-between px-4 py-3 border-b transition-all",
    "        ${isOver ? 'bg-blue-600 border-blue-500' : 'bg-slate-50 dark:bg-slate-900 border-slate-100 dark:border-slate-800'}`}>",
    "        <div className='flex items-center gap-2'>",
    "          <Users size={13} className={isOver ? 'text-blue-100' : 'text-slate-400'} />",
    "          <span className={`text-xs font-extrabold ${isOver ? 'text-white' : 'text-foreground'}`}>{label}</span>",
    "        </div>",
    "        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full",
    "          ${isOver ? 'bg-white/20 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-400'}`}>{people.length}</span>",
    "      </div>",
    "      <div className={`flex-1 p-3 transition-all ${isOver ? 'bg-blue-50/40 dark:bg-blue-950/15' : 'bg-white dark:bg-slate-900/50'}`}>",
    "        {people.length > 0 ? (",
    "          <div className='flex flex-wrap gap-1.5'>",
    "            {people.map(p => <PersonChip key={p.id} person={p} inCard sourceId={`card-${id}-${p.id}`} onRemove={() => onRemove(p.id)} />)}",
    "          </div>",
    "        ) : (",
    "          <div className={`flex-1 flex flex-col items-center justify-center rounded-lg border border-dashed min-h-[80px]",
    "            ${isOver ? 'border-blue-400 bg-blue-50/60' : 'border-slate-200 dark:border-slate-800'}`}>",
    "            <span className={`text-[10px] font-semibold uppercase tracking-wide",
    "              ${isOver ? 'text-blue-500' : 'text-slate-300 dark:text-slate-700'}`}>",
    "              {isOver ? 'Drop to assign' : 'Drop students here'}",
    "            </span>",
    "          </div>",
    "        )}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "/* ── Main Board ─────────────────────────────── */",
    "export default function StudentClassBoard() {",
    "  const [assignment, setAssignment] = useState<Record<string,string>>({});",
    "  const [activePerson, setActivePerson] = useState<Person|null>(null);",
    "  const [search, setSearch] = useState('');",
    "",
    "  const sensors = useSensors(",
    "    useSensor(PointerSensor, { activationConstraint: { distance: 4 } }),",
    "    useSensor(MouseSensor,   { activationConstraint: { distance: 4 } }),",
    "    useSensor(TouchSensor,   { activationConstraint: { delay: 150, tolerance: 8 } }),",
    "  );",
    "",
    "  const filtered = STUDENTS.filter(p => p.name.toLowerCase().includes(search.toLowerCase()));",
    "  const unassigned = filtered.filter(p => !assignment[p.id]);",
    "  const assigned   = filtered.filter(p => !!assignment[p.id]);",
    "",
    "  const cardLabelMap = Object.fromEntries(CARDS.map(c => [c.id, c.label]));",
    "",
    "  const handleDragEnd = (e: any) => {",
    "    const { active, over } = e;",
    "    setActivePerson(null);",
    "    if (!over) return;",
    "    const person = active.data.current?.person as Person;",
    "    if (!person || !String(over.id).startsWith('card-')) return;",
    "    setAssignment(prev => ({ ...prev, [person.id]: String(over.id) }));",
    "  };",
    "",
    "  return (",
    "    <DndContext sensors={sensors} onDragStart={e => setActivePerson(e.active.data.current?.person)} onDragEnd={handleDragEnd}>",
    "      <div className='flex flex-col gap-6'>",
    "        {/* Search Panel */}",
    "        <div className='bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm'>",
    "          <div className='relative mb-4'>",
    "            <Search size={15} className='absolute left-3 top-1/2 -translate-y-1/2 text-slate-400' />",
    "            <input type='text' placeholder='Search students…' value={search} onChange={e=>setSearch(e.target.value)}",
    "              className='w-full pl-9 pr-4 py-2.5 text-sm rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 outline-none focus:ring-2 focus:ring-blue-500/40' />",
    "          </div>",
    "          {unassigned.length > 0 && <div className='flex flex-wrap gap-2'>{unassigned.map(p => <PersonChip key={p.id} person={p} sourceId={`search-${p.id}`} />)}</div>}",
    "          {assigned.length > 0 && (",
    "            <div className='mt-3 flex flex-wrap gap-2'>",
    "              {assigned.map(p => <PersonChip key={p.id} person={p} assignedTo={cardLabelMap[assignment[p.id]]} sourceId={`search-${p.id}`} />)}",
    "            </div>",
    "          )}",
    "        </div>",
    "",
    "        {/* Class Cards */}",
    `        <div className="grid ${gridColClass} gap-4">`,
    "          {CARDS.map(card => (",
    "            <ClassCard key={card.id} id={card.id} label={card.label}",
    "              people={STUDENTS.filter(p => assignment[p.id] === card.id)}",
    "              onRemove={pid => setAssignment(prev => { const n={...prev}; delete n[pid]; return n; })} />",
    "          ))}",
    "        </div>",
    "      </div>",
    "      <DragOverlay>",
    "        {activePerson && <PersonChip person={activePerson} overlay />}",
    "      </DragOverlay>",
    "    </DndContext>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 2 ─────────────────────────────────────────────────────────────
export function generateWelcomeScreenCode(config: Record<string, any>): string {
  const name = String(config.name ?? "Developer");
  const systemName = String(config.systemName ?? "AB UI Kit");
  const nameColor = String(config.nameColor ?? "#ef4444");
  const duration = Number(config.animateDuration ?? 0.8);
  const delay = Number(config.delayBeforeOut ?? 1800);
  const skippable = Boolean(config.skippable ?? true);

  return [
    '"use client";',
    "",
    '/**',
    ' * AB UI — Welcome / Splash Screen',
    ' * Dependencies: framer-motion',
    ' */',
    "",
    'import { useEffect, useState } from "react";',
    'import { motion, AnimatePresence } from "framer-motion";',
    "",
    "export default function WelcomeSplashScreen() {",
    "  const [visible, setVisible] = useState(true);",
    "",
    "  useEffect(() => {",
    "    const timer = setTimeout(() => setVisible(false), " + delay + ");",
    "    return () => clearTimeout(timer);",
    "  }, []);",
    "",
    "  if (!visible) return null;",
    "",
    "  return (",
    "    <AnimatePresence>",
    "      <motion.div",
    '        className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-slate-950 select-none"',
    "        style={{ background: 'linear-gradient(135deg, #0f172a 0%, #020617 100%)' }}",
    "        initial={{ opacity: 0 }}",
    "        animate={{ opacity: 1 }}",
    "        exit={{ opacity: 0, scale: 1.05 }}",
    "        transition={{ duration: " + duration + ", ease: 'easeInOut' }}",
    skippable ? "        onClick={() => setVisible(false)}" : "",
    "      >",
    "        <div className='text-center px-4'>",
    "          <motion.h1",
    '            className="text-5xl font-bold tracking-tight text-white"',
    "            initial={{ y: 20, opacity: 0 }}",
    "            animate={{ y: 0, opacity: 1 }}",
    "            transition={{ delay: 0.2, duration: 0.6 }}",
    "          >",
    '            Hello, <span style={{ color: "' + nameColor + '" }}>' + name + "</span>",
    "          </motion.h1>",
    "          <motion.p",
    '            className="text-lg text-slate-400 font-light mt-2"',
    "            initial={{ y: 15, opacity: 0 }}",
    "            animate={{ y: 0, opacity: 1 }}",
    "            transition={{ delay: 0.4, duration: 0.6 }}",
    "          >",
    "            " + systemName,
    "          </motion.p>",
    "        </div>",
    skippable ? '        <p className="absolute bottom-8 text-xs text-slate-500">Click anywhere to skip</p>' : "",
    "      </motion.div>",
    "    </AnimatePresence>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — AG Grid ────────────────────────────────────────────────────
export function generateAGGridCode(config: Record<string, any>): string {
  const rowHeight = Number(config.rowHeight ?? 48);
  const pagination = Boolean(config.enablePagination ?? true);

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — AG Grid Community Variant",
    " * Dependencies: ag-grid-react  ag-grid-community",
    " */",
    "",
    'import React, { useEffect, useState } from "react";',
    'import { AgGridReact } from "ag-grid-react";',
    'import { AllCommunityModule, themeQuartz, colorSchemeDark } from "ag-grid-community";',
    "",
    "const lightTheme = themeQuartz;",
    "const darkTheme  = themeQuartz.withPart(colorSchemeDark);",
    "",
    "export default function AGGridDemo() {",
    "  const [rowData] = useState([",
    "    { id: 101, name: 'Alice Johnson', department: 'Engineering', status: 'Active', salary: 95000 },",
    "    { id: 102, name: 'Bob Smith',     department: 'Design',      status: 'Active', salary: 78000 },",
    "    { id: 103, name: 'Carol Davis',   department: 'Product',     status: 'On Leave', salary: 88000 },",
    "  ]);",
    "",
    "  const [gridTheme, setGridTheme] = useState(lightTheme);",
    "",
    "  useEffect(() => {",
    "    const isDark = document.documentElement.classList.contains('dark');",
    "    setGridTheme(isDark ? darkTheme : lightTheme);",
    "    const obs = new MutationObserver(() => {",
    "      setGridTheme(document.documentElement.classList.contains('dark') ? darkTheme : lightTheme);",
    "    });",
    "    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });",
    "    return () => obs.disconnect();",
    "  }, []);",
    "",
    "  const columnDefs = [",
    "    { field: 'id',         headerName: 'ID',         width: 90 },",
    "    { field: 'name',       headerName: 'Name',       flex: 1 },",
    "    { field: 'department', headerName: 'Department', flex: 1 },",
    "    { field: 'status',     headerName: 'Status',     width: 130 },",
    "    { field: 'salary',     headerName: 'Salary',     width: 130,",
    "      valueFormatter: p => typeof p.value === 'number' ? `$${p.value.toLocaleString()}` : '' },",
    "  ];",
    "",
    "  return (",
    '    <div className="w-full h-[400px] rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800">',
    "      <AgGridReact",
    "        modules={[AllCommunityModule]}",
    "        theme={gridTheme}",
    "        rowData={rowData}",
    "        columnDefs={columnDefs}",
    "        rowHeight={" + rowHeight + "}",
    "        pagination={" + pagination + "}",
    "        paginationPageSize={10}",
    "        defaultColDef={{ resizable: true, sortable: true }}",
    "      />",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — Custom CSS Table ──────────────────────────────────────────
export function generateCustomTableCode(_config: Record<string, any>): string {
  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Lightweight Custom CSS Table (zero external deps)",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { ChevronUp, ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";',
    "",
    "const SAMPLE = [",
    "  { id: 101, name: 'Alice Johnson', department: 'Engineering', status: 'Active',   salary: 95000, rating: 4.8 },",
    "  { id: 102, name: 'Bob Smith',     department: 'Design',      status: 'Active',   salary: 78000, rating: 4.2 },",
    "  { id: 103, name: 'Carol Davis',   department: 'Product',     status: 'On Leave', salary: 88000, rating: 4.5 },",
    "];",
    "",
    "export default function CustomTable() {",
    "  const [sortField, setSortField]     = useState<string|null>(null);",
    "  const [sortDir, setSortDir]         = useState<'asc'|'desc'>('asc');",
    "  const [page, setPage]               = useState(1);",
    "  const pageSize = 5;",
    "",
    "  const sorted = [...SAMPLE].sort((a,b) => {",
    "    if (!sortField) return 0;",
    "    const av = (a as any)[sortField], bv = (b as any)[sortField];",
    "    return sortDir === 'asc' ? (av > bv ? 1 : -1) : (bv > av ? 1 : -1);",
    "  });",
    "",
    "  const rows = sorted.slice((page-1)*pageSize, page*pageSize);",
    "  const total = Math.ceil(SAMPLE.length / pageSize);",
    "",
    "  const handleSort = (f: string) => {",
    "    if (sortField === f) setSortDir(d => d === 'asc' ? 'desc' : 'asc');",
    "    else { setSortField(f); setSortDir('asc'); }",
    "  };",
    "",
    "  return (",
    '    <div className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">',
    "      <div className='overflow-x-auto'>",
    "        <table className='w-full text-left text-sm'>",
    "          <thead>",
    "            <tr className='bg-slate-50 dark:bg-slate-950/20 border-b border-slate-200 dark:border-slate-800 text-slate-500 font-bold'>",
    "              {['id','name','department','status','salary'].map(f => (",
    "                <th key={f} onClick={() => handleSort(f)} className='px-6 py-4 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-800 uppercase text-xs'>",
    "                  {f} {sortField===f && (sortDir==='asc' ? <ChevronUp size={12} className='inline' /> : <ChevronDown size={12} className='inline' />)}",
    "                </th>",
    "              ))}",
    "            </tr>",
    "          </thead>",
    "          <tbody className='divide-y divide-slate-100 dark:divide-slate-800'>",
    "            {rows.map(r => (",
    "              <tr key={r.id} className='hover:bg-slate-50/50 dark:hover:bg-slate-800/20'>",
    "                <td className='px-6 py-4 font-mono'>{r.id}</td>",
    "                <td className='px-6 py-4 font-bold'>{r.name}</td>",
    "                <td className='px-6 py-4'>{r.department}</td>",
    "                <td className='px-6 py-4'><span className='px-2 py-0.5 rounded-full text-xs font-bold bg-green-100 text-green-800'>{r.status}</span></td>",
    "                <td className='px-6 py-4'>${r.salary.toLocaleString()}</td>",
    "              </tr>",
    "            ))}",
    "          </tbody>",
    "        </table>",
    "      </div>",
    "      <div className='flex items-center justify-between px-6 py-3 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-500'>",
    "        <span>Page <b>{page}</b> of <b>{total}</b></span>",
    "        <div className='flex gap-1'>",
    "          <button onClick={() => setPage(p => Math.max(1,p-1))} disabled={page===1} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronLeft size={14}/></button>",
    "          <button onClick={() => setPage(p => Math.min(total,p+1))} disabled={page===total} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronRight size={14}/></button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — Card Grid ─────────────────────────────────────────────────
export function generateCardGridCode(config: Record<string, any>): string {
  const columns = Number(config.columns ?? 3);

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Visual Product Card Grid",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { Sparkles } from "lucide-react";',
    "",
    "const PRODUCTS = [",
    "  { id: 201, name: 'Wireless Headphones', category: 'Electronics', price: 99,  rating: 4.5, status: 'In Stock'   },",
    "  { id: 202, name: 'Running Shoes',        category: 'Apparel',     price: 79,  rating: 4.1, status: 'Low Stock'  },",
    "  { id: 203, name: 'Espresso Machine',     category: 'Kitchen',     price: 199, rating: 4.8, status: 'In Stock'   },",
    "  { id: 204, name: 'Yoga Mat Pro',         category: 'Fitness',     price: 45,  rating: 4.3, status: 'Out of Stock'},",
    "];",
    "",
    "export default function ProductCardGrid() {",
    "  const [active, setActive] = useState('All');",
    "  const cats = ['All', ...Array.from(new Set(PRODUCTS.map(p => p.category)))];",
    "  const filtered = active === 'All' ? PRODUCTS : PRODUCTS.filter(p => p.category === active);",
    "",
    "  return (",
    "    <div className='space-y-4'>",
    "      <div className='flex gap-2 flex-wrap'>",
    "        {cats.map(c => (",
    "          <button key={c} onClick={() => setActive(c)}",
    "            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${active===c ? 'bg-blue-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-500 hover:text-foreground'}`}>",
    "            {c}",
    "          </button>",
    "        ))}",
    "      </div>",
    `      <div className="grid grid-cols-1 md:grid-cols-${columns} gap-5">`,
    "        {filtered.map(p => (",
    "          <div key={p.id} className='border border-slate-200 dark:border-slate-800 rounded-xl p-4 bg-white dark:bg-slate-900 hover:shadow-md transition-shadow'>",
    "            <div className='w-full h-28 rounded-lg bg-gradient-to-br from-blue-500/10 to-purple-500/10 flex items-center justify-center mb-3'>",
    "              <Sparkles size={20} className='text-blue-400/50' />",
    "            </div>",
    "            <span className='text-[10px] font-bold uppercase text-slate-400'>{p.category}</span>",
    "            <h4 className='text-sm font-bold text-foreground mt-0.5'>{p.name}</h4>",
    "            <div className='flex justify-between mt-3'>",
    "              <span className='text-base font-extrabold text-foreground'>${p.price}</span>",
    "              <span className='text-xs text-yellow-500 font-bold'>★ {p.rating}</span>",
    "            </div>",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — TanStack Table ────────────────────────────────────────────
export function generateTanStackCode(_config: Record<string, any>): string {
  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — TanStack React Table (headless)",
    " * Dependencies: @tanstack/react-table  lucide-react",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { useReactTable, getCoreRowModel, getSortedRowModel, getPaginationRowModel, flexRender, createColumnHelper } from "@tanstack/react-table";',
    'import { ArrowUpDown, ChevronUp, ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";',
    "",
    "interface Row { id: number; name: string; department: string; salary: number; }",
    "const columnHelper = createColumnHelper<Row>();",
    "",
    "const DATA: Row[] = [",
    "  { id: 101, name: 'Alice Johnson', department: 'Engineering', salary: 95000 },",
    "  { id: 102, name: 'Bob Smith',     department: 'Design',      salary: 78000 },",
    "  { id: 103, name: 'Carol Davis',   department: 'Product',     salary: 88000 },",
    "];",
    "",
    "export default function TanStackTableDemo() {",
    "  const [sorting, setSorting] = useState([]);",
    "",
    "  const columns = [",
    "    columnHelper.accessor('id',         { header: 'ID' }),",
    "    columnHelper.accessor('name',       { header: 'Name',       cell: i => <b>{i.getValue()}</b> }),",
    "    columnHelper.accessor('department', { header: 'Department' }),",
    "    columnHelper.accessor('salary',     { header: 'Salary',     cell: i => `$${i.getValue().toLocaleString()}` }),",
    "  ];",
    "",
    "  const table = useReactTable({",
    "    data: DATA, columns,",
    "    state: { sorting },",
    "    onSortingChange: setSorting as any,",
    "    getCoreRowModel: getCoreRowModel(),",
    "    getSortedRowModel: getSortedRowModel(),",
    "    getPaginationRowModel: getPaginationRowModel(),",
    "    initialState: { pagination: { pageSize: 5 } },",
    "  });",
    "",
    "  return (",
    '    <div className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">',
    "      <div className='overflow-x-auto'>",
    "        <table className='w-full text-left text-sm'>",
    "          <thead>",
    "            {table.getHeaderGroups().map(hg => (",
    "              <tr key={hg.id} className='bg-slate-50 dark:bg-slate-950/20 border-b border-slate-200 dark:border-slate-800 text-slate-500 font-bold'>",
    "                {hg.headers.map(h => (",
    "                  <th key={h.id} onClick={h.column.getToggleSortingHandler()} className='px-6 py-4 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-800 text-xs uppercase'>",
    "                    <div className='flex items-center gap-1.5'>",
    "                      {flexRender(h.column.columnDef.header, h.getContext())}",
    "                      {{ asc: <ChevronUp size={12} className='text-blue-500'/>, desc: <ChevronDown size={12} className='text-blue-500'/> }[h.column.getIsSorted() as string] ?? <ArrowUpDown size={11} />}",
    "                    </div>",
    "                  </th>",
    "                ))}",
    "              </tr>",
    "            ))}",
    "          </thead>",
    "          <tbody className='divide-y divide-slate-100 dark:divide-slate-800'>",
    "            {table.getRowModel().rows.map(row => (",
    "              <tr key={row.id} className='hover:bg-slate-50/50 dark:hover:bg-slate-800/20'>",
    "                {row.getVisibleCells().map(cell => (",
    "                  <td key={cell.id} className='px-6 py-4'>",
    "                    {flexRender(cell.column.columnDef.cell, cell.getContext())}",
    "                  </td>",
    "                ))}",
    "              </tr>",
    "            ))}",
    "          </tbody>",
    "        </table>",
    "      </div>",
    "      <div className='flex items-center justify-between px-6 py-3 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-500'>",
    "        <span>Page <b>{table.getState().pagination.pageIndex+1}</b> of <b>{table.getPageCount()||1}</b></span>",
    "        <div className='flex gap-1'>",
    "          <button onClick={()=>table.previousPage()} disabled={!table.getCanPreviousPage()} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronLeft size={14}/></button>",
    "          <button onClick={()=>table.nextPage()}     disabled={!table.getCanNextPage()}    className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronRight size={14}/></button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Design Sidebar ────────────────────────────────────────────────────────
export function generateDesignSidebarCode(config: Record<string, any>): string {
  const variant = String(config.variant ?? "default");
  const accent = String(config.accent ?? "blue");
  const defaultCollapsed = Boolean(config.defaultCollapsed ?? false);
  const showSearch = Boolean(config.showSearch ?? true);
  const showUser = Boolean(config.showUser ?? true);

  const accentActive: Record<string, string> = {
    blue:    "bg-blue-600 text-white shadow-blue-500/25",
    violet:  "bg-violet-600 text-white shadow-violet-500/25",
    rose:    "bg-rose-600 text-white shadow-rose-500/25",
    emerald: "bg-emerald-600 text-white shadow-emerald-500/25",
    amber:   "bg-amber-500 text-white shadow-amber-400/25",
  };

  const accentBadge: Record<string, string> = {
    blue:    "bg-blue-600 text-white",
    violet:  "bg-violet-600 text-white",
    rose:    "bg-rose-600 text-white",
    emerald: "bg-emerald-600 text-white",
    amber:   "bg-amber-500 text-white",
  };

  const accentGradient: Record<string, string> = {
    blue:    "from-blue-500 to-purple-600",
    violet:  "from-violet-500 to-purple-600",
    rose:    "from-rose-500 to-pink-600",
    emerald: "from-emerald-500 to-teal-600",
    amber:   "from-amber-500 to-orange-500",
  };

  const variantAside: Record<string, string> = {
    default:  "bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800",
    floating: "bg-white dark:bg-slate-900 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 m-3",
    minimal:  "bg-transparent border-r border-slate-100 dark:border-slate-800/50",
    glass:    "bg-white/70 dark:bg-slate-900/70 backdrop-blur-xl border-r border-white/20 dark:border-white/5",
  };

  const activeClass = accentActive[accent] ?? accentActive.blue;
  const badgeClass = accentBadge[accent] ?? accentBadge.blue;
  const gradientClass = accentGradient[accent] ?? accentGradient.blue;
  const asideClass = variantAside[variant] ?? variantAside.default;

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Animated Design Sidebar",
    " * Dependencies: framer-motion  lucide-react",
    " * Variant: " + variant + "  |  Accent: " + accent,
    " */",
    "",
    'import React, { useState } from "react";',
    'import { motion, AnimatePresence } from "framer-motion";',
    'import {',
    '  Home, LayoutDashboard, Settings, Users, FileText,',
    '  Bell, ChevronLeft, ChevronRight, Search, BarChart2,',
    '  Inbox, LogOut, Flame, X, Menu,',
    '} from "lucide-react";',
    "",
    "interface NavItem {",
    "  id: string;",
    "  label: string;",
    "  icon: React.ElementType;",
    "  badge?: number;",
    "  section?: string;",
    "}",
    "",
    "const NAV_ITEMS: NavItem[] = [",
    '  { id: "home",      label: "Home",      icon: Home,            section: "Main" },',
    '  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, section: "Main" },',
    '  { id: "inbox",     label: "Inbox",     icon: Inbox,           badge: 4,  section: "Main" },',
    '  { id: "analytics", label: "Analytics", icon: BarChart2,       section: "Main" },',
    '  { id: "users",     label: "Users",     icon: Users,           section: "Management" },',
    '  { id: "reports",   label: "Reports",   icon: FileText,        section: "Management" },',
    '  { id: "alerts",    label: "Alerts",    icon: Bell,            badge: 12, section: "Management" },',
    '  { id: "settings",  label: "Settings",  icon: Settings,        section: "System" },',
    "];",
    "",
    "const sidebarVariants = {",
    "  expanded:  { width: 256 },",
    "  collapsed: { width: 72 },",
    "};",
    "",
    "export default function DesignSidebar() {",
    "  const [collapsed, setCollapsed] = useState(" + defaultCollapsed + ");",
    '  const [activeId, setActiveId]   = useState("dashboard");',
    "  const [search, setSearch]       = useState(\"\");",
    "  const [mobileOpen, setMobileOpen] = useState(false);",
    "",
    "  const sections = Array.from(new Set(NAV_ITEMS.map((i) => i.section!)));",
    "  const filtered  = search.trim()",
    "    ? NAV_ITEMS.filter((i) => i.label.toLowerCase().includes(search.toLowerCase()))",
    "    : NAV_ITEMS;",
    "",
    "  return (",
    "    <div className=\"flex h-screen\">",
    "      {/* Mobile trigger */}",
    "      <button",
    "        onClick={() => setMobileOpen(true)}",
    "        className=\"md:hidden fixed top-4 left-4 z-50 p-2 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm cursor-pointer\"",
    "      >",
    "        <Menu size={20} />",
    "      </button>",
    "",
    "      {/* Mobile backdrop */}",
    "      <AnimatePresence>",
    "        {mobileOpen && (",
    "          <motion.div",
    "            className=\"md:hidden fixed inset-0 z-40 bg-black/50 backdrop-blur-sm\"",
    "            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}",
    "            onClick={() => setMobileOpen(false)}",
    "          />",
    "        )}",
    "      </AnimatePresence>",
    "",
    "      {/* Desktop sidebar */}",
    "      <motion.aside",
    '        className="hidden md:flex flex-col h-full overflow-hidden ' + asideClass + '"',
    "        variants={sidebarVariants}",
    "        initial={false}",
    "        animate={collapsed ? \"collapsed\" : \"expanded\"}",
    "        transition={{ type: \"spring\", stiffness: 300, damping: 30 }}",
    "      >",
    "        {/* Header */}",
    "        <div className=\"flex items-center justify-between px-4 h-16 border-b border-slate-100 dark:border-slate-800/80 shrink-0\">",
    "          <AnimatePresence mode=\"wait\">",
    "            {!collapsed ? (",
    "              <motion.div key=\"brand\" className=\"flex items-center gap-2.5\"",
    "                initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }}>",
    "                <Flame className=\"w-5 h-5 text-blue-500 fill-blue-500\" />",
    `                <span className="font-extrabold text-sm bg-gradient-to-r ${gradientClass} bg-clip-text text-transparent">`,
    "                  AB UI",
    "                </span>",
    "              </motion.div>",
    "            ) : (",
    "              <motion.div key=\"icon\" className=\"mx-auto\"",
    "                initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.8 }}>",
    "                <Flame className=\"w-5 h-5 text-blue-500 fill-blue-500\" />",
    "              </motion.div>",
    "            )}",
    "          </AnimatePresence>",
    "          <motion.button onClick={() => setCollapsed(!collapsed)}",
    "            className=\"p-1.5 rounded-md hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 cursor-pointer\"",
    "            whileTap={{ scale: 0.85 }}>",
    "            {collapsed ? <ChevronRight size={15} /> : <ChevronLeft size={15} />}",
    "          </motion.button>",
    "        </div>",
    "",
    showSearch ? [
      "        {/* Search */}",
      "        <AnimatePresence>",
      "          {!collapsed && (",
      "            <motion.div className=\"px-3 pt-3 pb-1\"",
      "              initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: \"auto\" }} exit={{ opacity: 0, height: 0 }}>",
      "              <div className=\"relative\">",
      "                <Search size={13} className=\"absolute left-3 top-1/2 -translate-y-1/2 text-slate-400\" />",
      "                <input type=\"text\" value={search} onChange={(e) => setSearch(e.target.value)}",
      "                  placeholder=\"Search…\"",
      "                  className=\"w-full pl-8 pr-3 py-2 text-xs rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 outline-none focus:ring-2 focus:ring-blue-500/40\" />",
      "              </div>",
      "            </motion.div>",
      "          )}",
      "        </AnimatePresence>",
    ].join("\n") : "",
    "",
    "        {/* Nav */}",
    "        <nav className=\"flex-1 overflow-y-auto px-2 py-3 space-y-4\">",
    "          {sections.map((section) => {",
    "            const items = filtered.filter((i) => i.section === section);",
    "            if (items.length === 0) return null;",
    "            return (",
    "              <div key={section}>",
    "                <AnimatePresence>",
    "                  {!collapsed && (",
    "                    <motion.span className=\"block px-3 mb-1.5 text-[9px] font-bold uppercase tracking-widest text-slate-400\"",
    "                      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>",
    "                      {section}",
    "                    </motion.span>",
    "                  )}",
    "                </AnimatePresence>",
    "                <div className=\"space-y-0.5\">",
    "                  {items.map((item) => {",
    "                    const active = item.id === activeId;",
    "                    const Icon   = item.icon;",
    "                    return (",
    "                      <motion.button key={item.id} onClick={() => setActiveId(item.id)} whileTap={{ scale: 0.97 }} layout",
    "                        className={`group w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-semibold transition-colors cursor-pointer",
    "                          ${active",
    `                            ? "${activeClass} shadow-md"`,
    "                            : \"text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800/60 hover:text-foreground\"",
    "                          } ${collapsed ? \"justify-center\" : \"\"}`}",
    "                      >",
    "                        <Icon size={17} className={`shrink-0 ${active ? \"text-white\" : \"text-slate-400\"}`} />",
    "                        <AnimatePresence mode=\"wait\">",
    "                          {!collapsed && (",
    "                            <motion.span key=\"label\" className=\"flex-1 text-left text-xs truncate\"",
    "                              initial={{ opacity: 0, x: -6 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -6 }}>",
    "                              {item.label}",
    "                            </motion.span>",
    "                          )}",
    "                        </AnimatePresence>",
    "                        {item.badge !== undefined && !collapsed && (",
    `                          <span className={\`shrink-0 min-w-[18px] h-[18px] flex items-center justify-center rounded-full text-[10px] font-bold px-1 \${active ? "bg-white/20 text-white" : "${badgeClass}"}\`}>`,
    "                            {item.badge > 99 ? \"99+\" : item.badge}",
    "                          </span>",
    "                        )}",
    "                      </motion.button>",
    "                    );",
    "                  })}",
    "                </div>",
    "              </div>",
    "            );",
    "          })}",
    "        </nav>",
    "",
    showUser ? [
      "        {/* User row */}",
      "        <div className=\"p-3 border-t border-slate-100 dark:border-slate-800/80 shrink-0\">",
      "          <div className={`flex items-center gap-3 px-2 py-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50 cursor-pointer ${collapsed ? \"justify-center\" : \"\"}`}>",
      "            <div className=\"w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white text-xs font-bold shrink-0\">",
      "              AB",
      "            </div>",
      "            <AnimatePresence mode=\"wait\">",
      "              {!collapsed && (",
      "                <motion.div key=\"user\" className=\"flex-1 min-w-0\"",
      "                  initial={{ opacity: 0, x: -6 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -6 }}>",
      "                  <p className=\"text-xs font-bold text-foreground\">Alex Builder</p>",
      "                  <p className=\"text-[10px] text-slate-400\">alex@ab-ui.dev</p>",
      "                </motion.div>",
      "              )}",
      "            </AnimatePresence>",
      "            {!collapsed && <LogOut size={14} className=\"text-slate-400 shrink-0\" />}",
      "          </div>",
      "        </div>",
    ].join("\n") : "",
    "      </motion.aside>",
    "",
    "      {/* Main content placeholder */}",
    "      <main className=\"flex-1 p-8 bg-slate-50 dark:bg-slate-950\">",
    "        <h1 className=\"text-2xl font-bold text-foreground\">Content Area</h1>",
    "        <p className=\"text-slate-400 mt-2 text-sm\">Click nav items to switch the active state.</p>",
    "      </main>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── User Welcome Card ─────────────────────────────────────────────────────
export function generateUserWelcomeCardCode(config: Record<string, any>): string {
  const name          = String(config.name          ?? "Alex Johnson");
  const role          = String(config.role          ?? "engineer");
  const department    = String(config.department    ?? "Frontend Systems");
  const location      = String(config.location      ?? "San Francisco, CA");
  const theme         = String(config.theme         ?? "gradient");
  const layout        = String(config.layout        ?? "horizontal");
  const primaryColor  = String(config.primaryColor  ?? "#3b82f6");
  const secondaryColor= String(config.secondaryColor?? "#8b5cf6");
  const borderRadius  = Number(config.borderRadius  ?? 20);
  const showShimmer   = Boolean(config.showShimmer  ?? true);
  const showParticles = Boolean(config.showParticles?? true);
  const showStats     = Boolean(config.showStats    ?? true);
  const showActions   = Boolean(config.showActions  ?? true);

  const useBrandColors = theme === "brand";

  const cssFile = [
    "/* UserWelcomeCard.module.css */",
    "",
    "@keyframes shimmer {",
    "  0%   { transform: translateX(-120%) skewX(-15deg); opacity: 0.6; }",
    "  60%  { opacity: 0.3; }",
    "  100% { transform: translateX(220%)  skewX(-15deg); opacity: 0; }",
    "}",
    ".shimmer::after {",
    "  content: \"\";",
    "  position: absolute; inset: 0;",
    "  background: linear-gradient(105deg, transparent 35%, rgba(255,255,255,0.18) 50%, transparent 65%);",
    "  animation: shimmer 1.1s ease-out forwards;",
    "  pointer-events: none; border-radius: inherit;",
    "}",
    "",
    "@keyframes ringPulse {",
    "  0%   { box-shadow: 0 0 0 0   rgba(255,255,255,0.45); }",
    "  60%  { box-shadow: 0 0 0 10px rgba(255,255,255,0);   }",
    "  100% { box-shadow: 0 0 0 0   rgba(255,255,255,0);    }",
    "}",
    ".avatarPulse { animation: ringPulse 1.4s ease-out 0.5s 1 forwards; }",
    "",
    "@keyframes caretBlink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }",
    ".caret::after { content: \"|\"; display: inline-block; margin-left: 2px;",
    "  font-weight: 300; animation: caretBlink 0.9s step-end infinite; }",
    "",
    "@keyframes badgePop {",
    "  0%   { transform: scale(0.5) translateY(4px); opacity: 0; }",
    "  70%  { transform: scale(1.12) translateY(-1px); }",
    "  100% { transform: scale(1) translateY(0); opacity: 1; }",
    "}",
    ".badgePop { animation: badgePop 0.45s cubic-bezier(0.34,1.56,0.64,1) forwards; }",
    "",
    "@keyframes floatUp {",
    "  0%   { transform: translateY(0) scale(1);     opacity: 0.7; }",
    "  100% { transform: translateY(-38px) scale(0.4); opacity: 0; }",
    "}",
    ".particle { animation: floatUp var(--dur, 2s) ease-out var(--delay, 0s) infinite; }",
    "",
    "@property --angle { syntax: \"<angle>\"; initial-value: 0deg; inherits: false; }",
    "@keyframes borderSpin { to { --angle: 360deg; } }",
    ".borderSpin {",
    "  background: conic-gradient(from var(--angle), transparent 70%, rgba(255,255,255,0.25) 80%, transparent 90%);",
    "  animation: borderSpin 4s linear infinite;",
    "}",
  ].join("\n");

  const tsxFile = [
    '"use client";',
    "",
    "/**",
    " * AB UI — User Welcome Card",
    " * Role: " + role + " | Theme: " + theme + " | Layout: " + layout,
    " * Dependencies: framer-motion  lucide-react",
    " * Also requires: UserWelcomeCard.module.css (see CSS tab / separate file)",
    " */",
    "",
    'import React, { useEffect, useState, useRef } from "react";',
    'import { motion, AnimatePresence } from "framer-motion";',
    'import { GraduationCap, Cpu, Palette, Briefcase, ShieldCheck, Stethoscope,',
    '  Star, Clock, CheckCircle2, Bell, ChevronRight, MapPin } from "lucide-react";',
    'import styles from "./UserWelcomeCard.module.css";',
    "",
    "/* ── Role config ─────────────────────────────────── */",
    "const ROLE_CFG = {",
    "  student:  { label: 'Student',  Icon: GraduationCap, gradient: 'from-blue-600 via-blue-500 to-indigo-600',    badgeBg: 'bg-blue-500/20',    badgeText: 'text-blue-200',    glow: 'rgba(59,130,246,0.35)'  },",
    "  engineer: { label: 'Engineer', Icon: Cpu,           gradient: 'from-violet-600 via-purple-500 to-fuchsia-600',badgeBg: 'bg-violet-500/20',  badgeText: 'text-violet-200',  glow: 'rgba(139,92,246,0.35)'  },",
    "  designer: { label: 'Designer', Icon: Palette,       gradient: 'from-rose-500 via-pink-500 to-fuchsia-500',    badgeBg: 'bg-rose-500/20',    badgeText: 'text-rose-200',    glow: 'rgba(244,63,94,0.35)'   },",
    "  manager:  { label: 'Manager',  Icon: Briefcase,     gradient: 'from-amber-500 via-orange-500 to-red-500',     badgeBg: 'bg-amber-500/20',   badgeText: 'text-amber-200',   glow: 'rgba(245,158,11,0.35)'  },",
    "  admin:    { label: 'Admin',    Icon: ShieldCheck,   gradient: 'from-emerald-500 via-teal-500 to-cyan-600',    badgeBg: 'bg-emerald-500/20', badgeText: 'text-emerald-200', glow: 'rgba(16,185,129,0.35)'  },",
    "  doctor:   { label: 'Doctor',   Icon: Stethoscope,   gradient: 'from-sky-500 via-cyan-500 to-teal-500',        badgeBg: 'bg-sky-500/20',     badgeText: 'text-sky-200',     glow: 'rgba(14,165,233,0.35)'  },",
    "} as const;",
    "",
    "type UserRole = keyof typeof ROLE_CFG;",
    "",
    "const PARTICLES = [",
    "  { top: '20%', left: '10%', size: 6, dur: '2.2s', delay: '0s'   },",
    "  { top: '60%', left: '80%', size: 8, dur: '2.8s', delay: '0.4s' },",
    "  { top: '75%', left: '20%', size: 5, dur: '2.0s', delay: '0.8s' },",
    "  { top: '15%', left: '70%', size: 7, dur: '3.1s', delay: '0.2s' },",
    "  { top: '50%', left: '50%', size: 4, dur: '2.5s', delay: '1.1s' },",
    "];",
    "",
    "export default function UserWelcomeCard() {",
    "  const role: UserRole = '" + role + "';",
    "  const cfg = ROLE_CFG[role];",
    "  const RoleIcon = cfg.Icon;",
    "",
    "  const [displayName, setDisplayName] = useState('');",
    "  const [nameDone, setNameDone]       = useState(false);",
    "  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);",
    "  const fullName = '" + name + "';",
    "",
    "  useEffect(() => {",
    "    let i = 0;",
    "    const tick = () => {",
    "      i++;",
    "      setDisplayName(fullName.slice(0, i));",
    "      if (i < fullName.length) timerRef.current = setTimeout(tick, 48);",
    "      else setNameDone(true);",
    "    };",
    "    timerRef.current = setTimeout(tick, 520);",
    "    return () => { if (timerRef.current) clearTimeout(timerRef.current); };",
    "  }, []);",
    "",
    "  return (",
    "    <motion.div",
    "      className={`relative overflow-hidden select-none bg-gradient-to-br ${cfg.gradient} text-white p-6`}",
    "      style={{",
    useBrandColors
      ? "        background: 'linear-gradient(135deg, " + primaryColor + " 0%, " + secondaryColor + " 100%)',"
      : "",
    "        borderRadius: " + borderRadius + ",",
    "        boxShadow: `0 20px 60px -12px ${cfg.glow}, 0 8px 24px -8px rgba(0,0,0,0.3)`,",
    "      }}",
    "      initial={{ opacity: 0, y: 28, scale: 0.96 }}",
    "      animate={{ opacity: 1, y: 0,  scale: 1    }}",
    "      transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }}",
    "    >",
    showShimmer ? "      <div className={styles.shimmer + ' absolute inset-0 pointer-events-none'} style={{ borderRadius: " + borderRadius + " }} />" : "",
    "      <div className={`absolute inset-0 pointer-events-none rounded-[inherit] ${styles.borderSpin}`} style={{ borderRadius: " + borderRadius + " }} />",
    "",
    showParticles ? [
      "      <div className='absolute inset-0 pointer-events-none overflow-hidden' style={{ borderRadius: " + borderRadius + " }}>",
      "        {PARTICLES.map((p, i) => (",
      "          <div key={i} className={`absolute rounded-full bg-white/25 ${styles.particle}`}",
      "            style={{ top: p.top, left: p.left, width: p.size, height: p.size,",
      "              ['--dur' as string]: p.dur, ['--delay' as string]: p.delay }} />",
      "        ))}",
      "      </div>",
    ].join("\n") : "",
    "",
    "      <div className='relative z-10 flex flex-row items-start gap-5'>",
    "        {/* Avatar */}",
    "        <motion.div className={'relative shrink-0 ' + styles.avatarPulse}",
    "          initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}",
    "          transition={{ delay: 0.15, type: 'spring', stiffness: 260, damping: 18 }}>",
    "          <div className='w-16 h-16 rounded-2xl bg-white/20 border-2 border-white/30 flex items-center justify-center'>",
    "            <span className='text-xl font-extrabold text-white'>",
    "              {'" + name.split(" ").map((w: string) => w[0]).slice(0, 2).join("") + "'}",
    "            </span>",
    "          </div>",
    "          <div className='absolute -bottom-1 -right-1 w-4 h-4 bg-emerald-400 rounded-full border-2 border-white/50' />",
    "        </motion.div>",
    "",
    "        <div className='flex-1 min-w-0'>",
    "          <motion.p className='text-[11px] font-semibold uppercase tracking-widest mb-0.5 text-white/70'",
    "            initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.25 }}>",
    "            Good morning",
    "          </motion.p>",
    "          <div className='text-2xl font-extrabold text-white'>",
    "            <span>{displayName}</span>",
    "            {!nameDone && <span className={styles.caret} />}",
    "          </div>",
    "          <div className='flex items-center gap-2 mt-2 flex-wrap'>",
    "            <motion.div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold ${cfg.badgeBg} ${cfg.badgeText} ${styles.badgePop}`}",
    "              style={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}>",
    "              <RoleIcon size={12} />",
    "              <span>{cfg.label}</span>",
    "            </motion.div>",
    "            <motion.span className='text-[11px] text-white/70' initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.75 }}>",
    "              · " + department,
    "            </motion.span>",
    "          </div>",
    "          <motion.div className='flex items-center gap-1 mt-2 text-[11px] text-white/65'",
    "            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.9 }}>",
    "            <MapPin size={11} /><span>" + location + "</span>",
    "          </motion.div>",
    "        </div>",
    "      </div>",
    "",
    showStats ? [
      "      <motion.div className='h-px w-full my-5 bg-white/15' initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ delay: 0.55, duration: 0.5 }} style={{ transformOrigin: 'left' }} />",
      "      <motion.div className='grid grid-cols-3 gap-3' initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.65 }}>",
      "        {[{ icon: Star, value: '4.9', label: 'Rating' }, { icon: Clock, value: '2.3y', label: 'Tenure' }, { icon: CheckCircle2, value: '124', label: 'Tasks' }].map(({ icon: I, value, label }) => (",
      "          <div key={label} className='rounded-xl px-3 py-2.5 bg-white/10 border border-white/15'>",
      "            <div className='flex items-center gap-1.5'><I size={12} className='text-white/60' /><span className='text-base font-extrabold text-white'>{value}</span></div>",
      "            <span className='text-[10px] text-white/60'>{label}</span>",
      "          </div>",
      "        ))}",
      "      </motion.div>",
    ].join("\n") : "",
    "",
    showActions ? [
      "      <motion.div className='flex gap-2.5 mt-4' initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.78 }}>",
      "        <button className='flex-1 py-2.5 rounded-xl text-xs font-bold bg-white/15 border border-white/20 hover:bg-white/25 text-white cursor-pointer'>View Profile</button>",
      "        <button className='flex items-center gap-1 px-4 py-2.5 rounded-xl text-xs font-bold bg-white/20 hover:bg-white/30 border border-white/25 text-white cursor-pointer'>",
      "          <span>Dashboard</span><ChevronRight size={13} />",
      "        </button>",
      "      </motion.div>",
    ].join("\n") : "",
    "    </motion.div>",
    "  );",
    "}",
    "",
    "/* ── Paste UserWelcomeCard.module.css alongside this file ── */",
    "/*",
    cssFile.split("\n").map(l => " * " + l).join("\n"),
    " */",
  ].join("\n");

  return tsxFile;
}
