/* ─────────────────────────────────────────────────────────────────────────
   Code template generators — each function returns a clean JSX string
   that can be copied into a project.
   Using String concatenation (not nested template literals) to avoid
   interpolation clashes.
───────────────────────────────────────────────────────────────────────── */

// ── Feature 1 ─────────────────────────────────────────────────────────────
export function generateTagBoardCode(config: Record<string, any>): string {
  const cardCount = Number(config.cardCount ?? 12);
  const columns = Number(config.columns ?? 4);

  const gridColClass =
    columns === 1
      ? "grid-cols-1"
      : columns === 2
      ? "grid-cols-1 md:grid-cols-2"
      : columns === 3
      ? "grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
      : "grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4";

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Student Class Assignment Board",
    " * Dependencies: @dnd-kit/core  @dnd-kit/utilities  lucide-react",
    " */",
    "",
    'import React, { useState, useMemo } from "react";',
    'import { DndContext, DragOverlay, PointerSensor, MouseSensor, TouchSensor, useSensor, useSensors, useDraggable, useDroppable } from "@dnd-kit/core";',
    'import { CSS } from "@dnd-kit/utilities";',
    'import { UserCircle2, Users, Search, X } from "lucide-react";',
    "",
    "interface Person { id: string; name: string; }",
    "",
    "/* ── Mock roster (replace with your API call) ── */",
    "const STUDENTS: Person[] = [",
    '  { id: "s01", name: "Alice Johnson" },',
    '  { id: "s02", name: "Bob Smith" },',
    '  { id: "s03", name: "Carol Williams" },',
    '  // ... add more students',
    "];",
    "",
    "const CARDS = Array.from({ length: " + cardCount + " }, (_, i) => ({",
    "  id: `card-${i + 1}`,",
    "  label: `Class ${i + 1}`,",
    "}));",
    "",
    "/* ── PersonChip — drag from anywhere ─────────── */",
    "function PersonChip({ person, inCard, assignedTo, onRemove, overlay, sourceId }: {",
    "  person: Person; inCard?: boolean; assignedTo?: string; onRemove?: () => void;",
    "  overlay?: boolean; sourceId?: string;",
    "}) {",
    "  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({",
    "    id: sourceId ?? `person-${person.id}`,",
    "    data: { person },",
    "    disabled: overlay,",
    "  });",
    "  const style = transform ? { transform: CSS.Translate.toString(transform) } : undefined;",
    "",
    "  if (overlay) return (",
    '    <div className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg bg-blue-600 text-white text-xs font-bold shadow-xl cursor-grabbing pointer-events-none">',
    "      <UserCircle2 size={13} /><span>{person.name}</span>",
    "    </div>",
    "  );",
    "",
    "  return (",
    "    <div ref={setNodeRef} style={style} {...listeners} {...attributes}",
    "      className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold border select-none cursor-grab active:cursor-grabbing transition-all",
    "        ${isDragging ? 'opacity-20 scale-90' : inCard",
    "          ? 'bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100 dark:bg-blue-950/50 dark:text-blue-300 dark:border-blue-800'",
    "          : assignedTo",
    "          ? 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800'",
    "          : 'bg-white text-slate-700 border-slate-200 hover:border-blue-300 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700'",
    "        }`}",
    "    >",
    "      <UserCircle2 size={12} className=\"opacity-60\" />",
    "      <span>{person.name}</span>",
    "      {assignedTo && !inCard && (",
    '        <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-100 text-amber-600 dark:bg-amber-900/50 dark:text-amber-400">{assignedTo}</span>',
    "      )}",
    "      {inCard && onRemove && (",
    "        <button onPointerDown={(e)=>e.stopPropagation()} onClick={(e)=>{e.stopPropagation();onRemove();}}",
    '          className="w-4 h-4 flex items-center justify-center rounded hover:bg-blue-200 dark:hover:bg-blue-800 text-blue-400 cursor-pointer">',
    "          <X size={10} />",
    "        </button>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "/* ── ClassCard ───────────────────────────────── */",
    "function ClassCard({ id, label, people, onRemove }: { id: string; label: string; people: Person[]; onRemove: (pid: string) => void }) {",
    "  const { setNodeRef, isOver } = useDroppable({ id });",
    "  return (",
    "    <div ref={setNodeRef}",
    "      className={`flex flex-col rounded-xl border min-h-[160px] transition-all overflow-hidden",
    "        ${isOver ? 'border-blue-500 shadow-lg ring-2 ring-blue-500/20 scale-[1.02]' : 'border-slate-200 dark:border-slate-800'}`,",
    "    }>",
    "      <div className={`flex items-center justify-between px-4 py-3 border-b transition-all",
    "        ${isOver ? 'bg-blue-600 border-blue-500' : 'bg-slate-50 dark:bg-slate-900 border-slate-100 dark:border-slate-800'}`}>",
    "        <div className='flex items-center gap-2'>",
    "          <Users size={13} className={isOver ? 'text-blue-100' : 'text-slate-400'} />",
    "          <span className={`text-xs font-extrabold ${isOver ? 'text-white' : 'text-foreground'}`}>{label}</span>",
    "        </div>",
    "        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full",
    "          ${isOver ? 'bg-white/20 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-400'}`}>{people.length}</span>",
    "      </div>",
    "      <div className={`flex-1 p-3 transition-all ${isOver ? 'bg-blue-50/40 dark:bg-blue-950/15' : 'bg-white dark:bg-slate-900/50'}`}>",
    "        {people.length > 0 ? (",
    "          <div className='flex flex-wrap gap-1.5'>",
    "            {people.map(p => <PersonChip key={p.id} person={p} inCard sourceId={`card-${id}-${p.id}`} onRemove={() => onRemove(p.id)} />)}",
    "          </div>",
    "        ) : (",
    "          <div className={`flex-1 flex flex-col items-center justify-center rounded-lg border border-dashed min-h-[80px]",
    "            ${isOver ? 'border-blue-400 bg-blue-50/60' : 'border-slate-200 dark:border-slate-800'}`}>",
    "            <span className={`text-[10px] font-semibold uppercase tracking-wide",
    "              ${isOver ? 'text-blue-500' : 'text-slate-300 dark:text-slate-700'}`}>",
    "              {isOver ? 'Drop to assign' : 'Drop students here'}",
    "            </span>",
    "          </div>",
    "        )}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "/* ── Main Board ─────────────────────────────── */",
    "export default function StudentClassBoard() {",
    "  const [assignment, setAssignment] = useState<Record<string,string>>({});",
    "  const [activePerson, setActivePerson] = useState<Person|null>(null);",
    "  const [search, setSearch] = useState('');",
    "",
    "  const sensors = useSensors(",
    "    useSensor(PointerSensor, { activationConstraint: { distance: 4 } }),",
    "    useSensor(MouseSensor,   { activationConstraint: { distance: 4 } }),",
    "    useSensor(TouchSensor,   { activationConstraint: { delay: 150, tolerance: 8 } }),",
    "  );",
    "",
    "  const filtered = STUDENTS.filter(p => p.name.toLowerCase().includes(search.toLowerCase()));",
    "  const unassigned = filtered.filter(p => !assignment[p.id]);",
    "  const assigned   = filtered.filter(p => !!assignment[p.id]);",
    "",
    "  const cardLabelMap = Object.fromEntries(CARDS.map(c => [c.id, c.label]));",
    "",
    "  const handleDragEnd = (e: any) => {",
    "    const { active, over } = e;",
    "    setActivePerson(null);",
    "    if (!over) return;",
    "    const person = active.data.current?.person as Person;",
    "    if (!person || !String(over.id).startsWith('card-')) return;",
    "    setAssignment(prev => ({ ...prev, [person.id]: String(over.id) }));",
    "  };",
    "",
    "  return (",
    "    <DndContext sensors={sensors} onDragStart={e => setActivePerson(e.active.data.current?.person)} onDragEnd={handleDragEnd}>",
    "      <div className='flex flex-col gap-6'>",
    "        {/* Search Panel */}",
    "        <div className='bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm'>",
    "          <div className='relative mb-4'>",
    "            <Search size={15} className='absolute left-3 top-1/2 -translate-y-1/2 text-slate-400' />",
    "            <input type='text' placeholder='Search students…' value={search} onChange={e=>setSearch(e.target.value)}",
    "              className='w-full pl-9 pr-4 py-2.5 text-sm rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 outline-none focus:ring-2 focus:ring-blue-500/40' />",
    "          </div>",
    "          {unassigned.length > 0 && <div className='flex flex-wrap gap-2'>{unassigned.map(p => <PersonChip key={p.id} person={p} sourceId={`search-${p.id}`} />)}</div>}",
    "          {assigned.length > 0 && (",
    "            <div className='mt-3 flex flex-wrap gap-2'>",
    "              {assigned.map(p => <PersonChip key={p.id} person={p} assignedTo={cardLabelMap[assignment[p.id]]} sourceId={`search-${p.id}`} />)}",
    "            </div>",
    "          )}",
    "        </div>",
    "",
    "        {/* Class Cards */}",
    `        <div className="grid ${gridColClass} gap-4">`,
    "          {CARDS.map(card => (",
    "            <ClassCard key={card.id} id={card.id} label={card.label}",
    "              people={STUDENTS.filter(p => assignment[p.id] === card.id)}",
    "              onRemove={pid => setAssignment(prev => { const n={...prev}; delete n[pid]; return n; })} />",
    "          ))}",
    "        </div>",
    "      </div>",
    "      <DragOverlay>",
    "        {activePerson && <PersonChip person={activePerson} overlay />}",
    "      </DragOverlay>",
    "    </DndContext>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 2 ─────────────────────────────────────────────────────────────
export function generateWelcomeScreenCode(config: Record<string, any>): string {
  const name = String(config.name ?? "Developer");
  const systemName = String(config.systemName ?? "AB UI Kit");
  const nameColor = String(config.nameColor ?? "#ef4444");
  const duration = Number(config.animateDuration ?? 0.8);
  const delay = Number(config.delayBeforeOut ?? 1800);
  const skippable = Boolean(config.skippable ?? true);

  return [
    '"use client";',
    "",
    '/**',
    ' * AB UI — Welcome / Splash Screen',
    ' * Dependencies: framer-motion',
    ' */',
    "",
    'import { useEffect, useState } from "react";',
    'import { motion, AnimatePresence } from "framer-motion";',
    "",
    "export default function WelcomeSplashScreen() {",
    "  const [visible, setVisible] = useState(true);",
    "",
    "  useEffect(() => {",
    "    const timer = setTimeout(() => setVisible(false), " + delay + ");",
    "    return () => clearTimeout(timer);",
    "  }, []);",
    "",
    "  if (!visible) return null;",
    "",
    "  return (",
    "    <AnimatePresence>",
    "      <motion.div",
    '        className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-slate-950 select-none"',
    "        style={{ background: 'linear-gradient(135deg, #0f172a 0%, #020617 100%)' }}",
    "        initial={{ opacity: 0 }}",
    "        animate={{ opacity: 1 }}",
    "        exit={{ opacity: 0, scale: 1.05 }}",
    "        transition={{ duration: " + duration + ", ease: 'easeInOut' }}",
    skippable ? "        onClick={() => setVisible(false)}" : "",
    "      >",
    "        <div className='text-center px-4'>",
    "          <motion.h1",
    '            className="text-5xl font-bold tracking-tight text-white"',
    "            initial={{ y: 20, opacity: 0 }}",
    "            animate={{ y: 0, opacity: 1 }}",
    "            transition={{ delay: 0.2, duration: 0.6 }}",
    "          >",
    '            Hello, <span style={{ color: "' + nameColor + '" }}>' + name + "</span>",
    "          </motion.h1>",
    "          <motion.p",
    '            className="text-lg text-slate-400 font-light mt-2"',
    "            initial={{ y: 15, opacity: 0 }}",
    "            animate={{ y: 0, opacity: 1 }}",
    "            transition={{ delay: 0.4, duration: 0.6 }}",
    "          >",
    "            " + systemName,
    "          </motion.p>",
    "        </div>",
    skippable ? '        <p className="absolute bottom-8 text-xs text-slate-500">Click anywhere to skip</p>' : "",
    "      </motion.div>",
    "    </AnimatePresence>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — AG Grid ────────────────────────────────────────────────────
export function generateAGGridCode(config: Record<string, any>): string {
  const rowHeight = Number(config.rowHeight ?? 48);
  const pagination = Boolean(config.enablePagination ?? true);

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — AG Grid Community Variant",
    " * Dependencies: ag-grid-react  ag-grid-community",
    " */",
    "",
    'import React, { useEffect, useState } from "react";',
    'import { AgGridReact } from "ag-grid-react";',
    'import { AllCommunityModule, themeQuartz, colorSchemeDark } from "ag-grid-community";',
    "",
    "const lightTheme = themeQuartz;",
    "const darkTheme  = themeQuartz.withPart(colorSchemeDark);",
    "",
    "export default function AGGridDemo() {",
    "  const [rowData] = useState([",
    "    { id: 101, name: 'Alice Johnson', department: 'Engineering', status: 'Active', salary: 95000 },",
    "    { id: 102, name: 'Bob Smith',     department: 'Design',      status: 'Active', salary: 78000 },",
    "    { id: 103, name: 'Carol Davis',   department: 'Product',     status: 'On Leave', salary: 88000 },",
    "  ]);",
    "",
    "  const [gridTheme, setGridTheme] = useState(lightTheme);",
    "",
    "  useEffect(() => {",
    "    const isDark = document.documentElement.classList.contains('dark');",
    "    setGridTheme(isDark ? darkTheme : lightTheme);",
    "    const obs = new MutationObserver(() => {",
    "      setGridTheme(document.documentElement.classList.contains('dark') ? darkTheme : lightTheme);",
    "    });",
    "    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });",
    "    return () => obs.disconnect();",
    "  }, []);",
    "",
    "  const columnDefs = [",
    "    { field: 'id',         headerName: 'ID',         width: 90 },",
    "    { field: 'name',       headerName: 'Name',       flex: 1 },",
    "    { field: 'department', headerName: 'Department', flex: 1 },",
    "    { field: 'status',     headerName: 'Status',     width: 130 },",
    "    { field: 'salary',     headerName: 'Salary',     width: 130,",
    "      valueFormatter: p => typeof p.value === 'number' ? `$${p.value.toLocaleString()}` : '' },",
    "  ];",
    "",
    "  return (",
    '    <div className="w-full h-[400px] rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800">',
    "      <AgGridReact",
    "        modules={[AllCommunityModule]}",
    "        theme={gridTheme}",
    "        rowData={rowData}",
    "        columnDefs={columnDefs}",
    "        rowHeight={" + rowHeight + "}",
    "        pagination={" + pagination + "}",
    "        paginationPageSize={10}",
    "        defaultColDef={{ resizable: true, sortable: true }}",
    "      />",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — Custom CSS Table ──────────────────────────────────────────
export function generateCustomTableCode(_config: Record<string, any>): string {
  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Lightweight Custom CSS Table (zero external deps)",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { ChevronUp, ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";',
    "",
    "const SAMPLE = [",
    "  { id: 101, name: 'Alice Johnson', department: 'Engineering', status: 'Active',   salary: 95000, rating: 4.8 },",
    "  { id: 102, name: 'Bob Smith',     department: 'Design',      status: 'Active',   salary: 78000, rating: 4.2 },",
    "  { id: 103, name: 'Carol Davis',   department: 'Product',     status: 'On Leave', salary: 88000, rating: 4.5 },",
    "];",
    "",
    "export default function CustomTable() {",
    "  const [sortField, setSortField]     = useState<string|null>(null);",
    "  const [sortDir, setSortDir]         = useState<'asc'|'desc'>('asc');",
    "  const [page, setPage]               = useState(1);",
    "  const pageSize = 5;",
    "",
    "  const sorted = [...SAMPLE].sort((a,b) => {",
    "    if (!sortField) return 0;",
    "    const av = (a as any)[sortField], bv = (b as any)[sortField];",
    "    return sortDir === 'asc' ? (av > bv ? 1 : -1) : (bv > av ? 1 : -1);",
    "  });",
    "",
    "  const rows = sorted.slice((page-1)*pageSize, page*pageSize);",
    "  const total = Math.ceil(SAMPLE.length / pageSize);",
    "",
    "  const handleSort = (f: string) => {",
    "    if (sortField === f) setSortDir(d => d === 'asc' ? 'desc' : 'asc');",
    "    else { setSortField(f); setSortDir('asc'); }",
    "  };",
    "",
    "  return (",
    '    <div className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">',
    "      <div className='overflow-x-auto'>",
    "        <table className='w-full text-left text-sm'>",
    "          <thead>",
    "            <tr className='bg-slate-50 dark:bg-slate-950/20 border-b border-slate-200 dark:border-slate-800 text-slate-500 font-bold'>",
    "              {['id','name','department','status','salary'].map(f => (",
    "                <th key={f} onClick={() => handleSort(f)} className='px-6 py-4 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-800 uppercase text-xs'>",
    "                  {f} {sortField===f && (sortDir==='asc' ? <ChevronUp size={12} className='inline' /> : <ChevronDown size={12} className='inline' />)}",
    "                </th>",
    "              ))}",
    "            </tr>",
    "          </thead>",
    "          <tbody className='divide-y divide-slate-100 dark:divide-slate-800'>",
    "            {rows.map(r => (",
    "              <tr key={r.id} className='hover:bg-slate-50/50 dark:hover:bg-slate-800/20'>",
    "                <td className='px-6 py-4 font-mono'>{r.id}</td>",
    "                <td className='px-6 py-4 font-bold'>{r.name}</td>",
    "                <td className='px-6 py-4'>{r.department}</td>",
    "                <td className='px-6 py-4'><span className='px-2 py-0.5 rounded-full text-xs font-bold bg-green-100 text-green-800'>{r.status}</span></td>",
    "                <td className='px-6 py-4'>${r.salary.toLocaleString()}</td>",
    "              </tr>",
    "            ))}",
    "          </tbody>",
    "        </table>",
    "      </div>",
    "      <div className='flex items-center justify-between px-6 py-3 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-500'>",
    "        <span>Page <b>{page}</b> of <b>{total}</b></span>",
    "        <div className='flex gap-1'>",
    "          <button onClick={() => setPage(p => Math.max(1,p-1))} disabled={page===1} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronLeft size={14}/></button>",
    "          <button onClick={() => setPage(p => Math.min(total,p+1))} disabled={page===total} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronRight size={14}/></button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — Card Grid ─────────────────────────────────────────────────
export function generateCardGridCode(config: Record<string, any>): string {
  const columns = Number(config.columns ?? 3);

  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — Visual Product Card Grid",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { Sparkles } from "lucide-react";',
    "",
    "const PRODUCTS = [",
    "  { id: 201, name: 'Wireless Headphones', category: 'Electronics', price: 99,  rating: 4.5, status: 'In Stock'   },",
    "  { id: 202, name: 'Running Shoes',        category: 'Apparel',     price: 79,  rating: 4.1, status: 'Low Stock'  },",
    "  { id: 203, name: 'Espresso Machine',     category: 'Kitchen',     price: 199, rating: 4.8, status: 'In Stock'   },",
    "  { id: 204, name: 'Yoga Mat Pro',         category: 'Fitness',     price: 45,  rating: 4.3, status: 'Out of Stock'},",
    "];",
    "",
    "export default function ProductCardGrid() {",
    "  const [active, setActive] = useState('All');",
    "  const cats = ['All', ...Array.from(new Set(PRODUCTS.map(p => p.category)))];",
    "  const filtered = active === 'All' ? PRODUCTS : PRODUCTS.filter(p => p.category === active);",
    "",
    "  return (",
    "    <div className='space-y-4'>",
    "      <div className='flex gap-2 flex-wrap'>",
    "        {cats.map(c => (",
    "          <button key={c} onClick={() => setActive(c)}",
    "            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${active===c ? 'bg-blue-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-500 hover:text-foreground'}`}>",
    "            {c}",
    "          </button>",
    "        ))}",
    "      </div>",
    `      <div className="grid grid-cols-1 md:grid-cols-${columns} gap-5">`,
    "        {filtered.map(p => (",
    "          <div key={p.id} className='border border-slate-200 dark:border-slate-800 rounded-xl p-4 bg-white dark:bg-slate-900 hover:shadow-md transition-shadow'>",
    "            <div className='w-full h-28 rounded-lg bg-gradient-to-br from-blue-500/10 to-purple-500/10 flex items-center justify-center mb-3'>",
    "              <Sparkles size={20} className='text-blue-400/50' />",
    "            </div>",
    "            <span className='text-[10px] font-bold uppercase text-slate-400'>{p.category}</span>",
    "            <h4 className='text-sm font-bold text-foreground mt-0.5'>{p.name}</h4>",
    "            <div className='flex justify-between mt-3'>",
    "              <span className='text-base font-extrabold text-foreground'>${p.price}</span>",
    "              <span className='text-xs text-yellow-500 font-bold'>★ {p.rating}</span>",
    "            </div>",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

// ── Feature 3 — TanStack Table ────────────────────────────────────────────
export function generateTanStackCode(_config: Record<string, any>): string {
  return [
    '"use client";',
    "",
    "/**",
    " * AB UI — TanStack React Table (headless)",
    " * Dependencies: @tanstack/react-table  lucide-react",
    " */",
    "",
    'import React, { useState } from "react";',
    'import { useReactTable, getCoreRowModel, getSortedRowModel, getPaginationRowModel, flexRender, createColumnHelper } from "@tanstack/react-table";',
    'import { ArrowUpDown, ChevronUp, ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";',
    "",
    "interface Row { id: number; name: string; department: string; salary: number; }",
    "const columnHelper = createColumnHelper<Row>();",
    "",
    "const DATA: Row[] = [",
    "  { id: 101, name: 'Alice Johnson', department: 'Engineering', salary: 95000 },",
    "  { id: 102, name: 'Bob Smith',     department: 'Design',      salary: 78000 },",
    "  { id: 103, name: 'Carol Davis',   department: 'Product',     salary: 88000 },",
    "];",
    "",
    "export default function TanStackTableDemo() {",
    "  const [sorting, setSorting] = useState([]);",
    "",
    "  const columns = [",
    "    columnHelper.accessor('id',         { header: 'ID' }),",
    "    columnHelper.accessor('name',       { header: 'Name',       cell: i => <b>{i.getValue()}</b> }),",
    "    columnHelper.accessor('department', { header: 'Department' }),",
    "    columnHelper.accessor('salary',     { header: 'Salary',     cell: i => `$${i.getValue().toLocaleString()}` }),",
    "  ];",
    "",
    "  const table = useReactTable({",
    "    data: DATA, columns,",
    "    state: { sorting },",
    "    onSortingChange: setSorting as any,",
    "    getCoreRowModel: getCoreRowModel(),",
    "    getSortedRowModel: getSortedRowModel(),",
    "    getPaginationRowModel: getPaginationRowModel(),",
    "    initialState: { pagination: { pageSize: 5 } },",
    "  });",
    "",
    "  return (",
    '    <div className="w-full bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">',
    "      <div className='overflow-x-auto'>",
    "        <table className='w-full text-left text-sm'>",
    "          <thead>",
    "            {table.getHeaderGroups().map(hg => (",
    "              <tr key={hg.id} className='bg-slate-50 dark:bg-slate-950/20 border-b border-slate-200 dark:border-slate-800 text-slate-500 font-bold'>",
    "                {hg.headers.map(h => (",
    "                  <th key={h.id} onClick={h.column.getToggleSortingHandler()} className='px-6 py-4 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-800 text-xs uppercase'>",
    "                    <div className='flex items-center gap-1.5'>",
    "                      {flexRender(h.column.columnDef.header, h.getContext())}",
    "                      {{ asc: <ChevronUp size={12} className='text-blue-500'/>, desc: <ChevronDown size={12} className='text-blue-500'/> }[h.column.getIsSorted() as string] ?? <ArrowUpDown size={11} />}",
    "                    </div>",
    "                  </th>",
    "                ))}",
    "              </tr>",
    "            ))}",
    "          </thead>",
    "          <tbody className='divide-y divide-slate-100 dark:divide-slate-800'>",
    "            {table.getRowModel().rows.map(row => (",
    "              <tr key={row.id} className='hover:bg-slate-50/50 dark:hover:bg-slate-800/20'>",
    "                {row.getVisibleCells().map(cell => (",
    "                  <td key={cell.id} className='px-6 py-4'>",
    "                    {flexRender(cell.column.columnDef.cell, cell.getContext())}",
    "                  </td>",
    "                ))}",
    "              </tr>",
    "            ))}",
    "          </tbody>",
    "        </table>",
    "      </div>",
    "      <div className='flex items-center justify-between px-6 py-3 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-500'>",
    "        <span>Page <b>{table.getState().pagination.pageIndex+1}</b> of <b>{table.getPageCount()||1}</b></span>",
    "        <div className='flex gap-1'>",
    "          <button onClick={()=>table.previousPage()} disabled={!table.getCanPreviousPage()} className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronLeft size={14}/></button>",
    "          <button onClick={()=>table.nextPage()}     disabled={!table.getCanNextPage()}    className='p-1.5 rounded border hover:bg-slate-50 disabled:opacity-40'><ChevronRight size={14}/></button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}
